config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # mount Commontator::Engine => '/commontator'
  resources :articles
  # devise_for :admin_users, { class_name: 'User' }.merge(ActiveAdmin::Devise.config)
  # ActiveAdmin.routes(self)
  # devise_for :users # , controllers: { sessions: 'users/sessions' }
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # resources :users
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  # acts_as_commontable dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :ratings
  has_many :appreciators, through: :ratings, source: :user
  # has_many :comments, as: :commentable
  has_and_belongs_to_many :tags

  validates :author, presence: true
  validates_associated :author
  validates_length_of :description, maximum: 256

  def rating
    ratings.average(:stars)
  end

  rails_admin do
    configure :author do
      label 'Author: '
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @articles = Article.where(published: true).order('published_at DESC')
  end

  def new
    if current_user.role?(:admin) && params[:author]
      @article.author = User.where(id: params[:author]).first
    else
      @article.author = current_user
    end
  end

  def create
    if @article.published
      @article.published_at = Time.now
    end
    if @article.save
      flash[:success] = "Post was created successfully"
      redirect_to @article
    else
      render :new
    end
  end

  def update
    if @article.published
      @article.published_at = Time.now
    end
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show
    commontator_thread_show(@article)
  end

  private
    def article_params
      params.require(:article).permit(:title, :description, :text, :author, :published, :published_at, :lock_version)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@article.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :lock_version %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, size: 'autox3', class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, id: "text-editor" %>
  </div>

  <div class="form-group form-check">
    <%= f.check_box :published %>
    <%= f.label 'Publish?', class: "control-label" %>
  </div>

  <div class="form-group">
    <%= f.button 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'layouts/newspaper' %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% if !@article.published %>
  <% if current_user != @article.author %>
    <%= render_404%>  
  <% end %>
<% end %>

<div class="col-xs-12 single-content">
  <div class="article-content">
    <div class="title">
      <h1><strong>
          <%= @article.title %>
      </strong></h1>
      <hr>
    </div>

    <div>
      <%= markdown(@article.text) %>
    </div>
    <div class="author">
      <span class="mb-2 text-muted">
        By <%= @article.author.email %>, <%= @article.published_at.strftime("%d/%m/%Y, %H:%M")%>
      </span>
    </div>
  </div>
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', articles_path %>
  <%= commontator_thread(@article) %>
</div>